using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class PlayerLife : MonoBehaviour
{
    private Animator anim;
    private Rigidbody2D rb;

    [SerializeField]
    private DeathScreen deathScreen;

    public int collectiblesGathered = 0;

    private void Start()
    {
        rb = GetComponent<Rigidbody2D>();
        anim = GetComponent<Animator>();
    }

    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.CompareTag("Hazard"))
        {
            Die();
        }
    }

    private void Die()
    {
        rb.bodyType = RigidbodyType2D.Static;
        SoundManager.PlaySound(SoundManager.Sound.PlayerDeath);
        anim.SetTrigger("death");
    }

    public void ShowScreen()
    {
        deathScreen.ShowDeathScreen();
    }
}
